services:
  frontend:
    build: ./frontend
    image: react-app
    restart: on-failure
    ports:
     - 3000:3000
    volumes:
     - ./frontend:/app
    depends_on:
     - backend

  backend:
    build: ./backend
    image: flask-app
    restart: on-failure
    ports:
     - 5000:5000
    environment:
     - MYSQL_HOST=db
     - MYSQL_USER=${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
     - MYSQL_DB=${MYSQL_DB}
    volumes:
     - ./backend:/app
    depends_on:
     - db

  db:
    image: mysql:5.7
    restart: on-failure
    ports:
     - 3306:3306
    environment:
     - MYSQL_DATABASE=${MYSQL_DB}
     - MYSQL_USER=${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
     - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
