services:
  
  api:
    build:
      context: ./back
    image: react-flask-app-api
    restart: always
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - my_network

  client:
    build:
      context: ./front
    image: react-flask-app-client
    restart: always
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - my_network
    ports:
      - "3000:80"

volumes:
  postgres:
    driver: local

networks:
  my_network:
    name: my_network
